/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://wirjoyt2ifcd3omvpg3xgxpynu.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-west-1:adf33950-8706-498a-baf5-10a48f28620a",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_tewDQpczA",
    "aws_user_pools_web_client_id": "7uvgtvo1jt70ov93fdm6ithnia",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplifyoncall0af15cffeb5b41f3ab44146b59b7f2f8a4763-dev",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
